defaults:
  - _self_
  - common: carcharhiniformes
  - preprocess: carcharhiniformes
  - plot: carcharhiniformes
  - experiment_tracking: local

data:
  dir: data
  index: index.csv
  out: data.csv