stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - conf/common/carcharhiniformes.yaml
    - conf/config.yaml
    - conf/preprocess/carcharhiniformes.yaml
    - data/limbatus.csv
    - data/spot_tail_shark.csv
    - src/preprocess.py
    outs:
    - data/chondrichthyes/carcharhiniformes/carcharhinus_limbatus/README.md
    - data/chondrichthyes/carcharhiniformes/carcharhinus_limbatus/data.csv
    - data/chondrichthyes/carcharhiniformes/carcharhinus_sorrah/README.md
    - data/chondrichthyes/carcharhiniformes/carcharhinus_sorrah/data.csv
    - data/chondrichthyes/carcharhiniformes/carcharhinus_tilstoni/README.md
    - data/chondrichthyes/carcharhiniformes/carcharhinus_tilstoni/data.csv
  plot_curves:
    cmd: python src/plot_curves.py
    deps:
    - conf/common/carcharhiniformes.yaml
    - conf/config.yaml
    - conf/experiment_tracking/local.yaml
    - conf/plot/carcharhiniformes.yaml
    - data/chondrichthyes/carcharhiniformes/carcharhinus_limbatus/data.csv
    - data/chondrichthyes/carcharhiniformes/carcharhinus_sorrah/data.csv
    - data/chondrichthyes/carcharhiniformes/carcharhinus_tilstoni/data.csv
    - src/plot_curves.py
    outs:
    - data/chondrichthyes/carcharhiniformes/carcharhinus_limbatus/stl_age.png
    - data/chondrichthyes/carcharhiniformes/carcharhinus_sorrah/stl_age.png
    - data/chondrichthyes/carcharhiniformes/carcharhinus_tilstoni/stl_age.png
